name: 删除旧版本固件和标签

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  delete_releases_and_tags:
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: 检出代码
        uses: actions/checkout@main
      
      - name: 配置Python运行环境
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: 安装PyGithub
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyGithub

      - name: 删除旧版本固件和标签
        run: python delete_releases_and_tags.py          
