name: 删除旧版本固件和标签

on:
  schedule:
    - cron: 0 4 * * *

  workflow_dispatch:

permissions:
  contents: write

jobs:
  delete_releases_and_tags:
    runs-on: ubuntu-24.04

    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      TZ: Asia/Shanghai

    steps:
      - name: 获取虚拟机信息
        run: |
          cpu_model=$(cat /proc/cpuinfo | grep 'model name' | head -n1 | awk -F ': ' '{print $2}')
          cpu_cores=$(cat /proc/cpuinfo | grep 'cpu cores' | head -n1 | awk -F ': ' '{print $2}')
          cpu_threads=$(nproc)
          mem_total=$(free -m | grep 'Mem' | awk '{print $2}')
          os_version=$(lsb_release -a | grep 'Description' | awk -F ':\t' '{print $2}')
          echo "CPU: $cpu_model $cpu_cores核心$cpu_threads线程"
          echo "内存: $mem_total MB"
          echo "操作系统: $os_version"
          echo "时间: $(date "+%Y-%m-%d %H:%M:%S")"
          echo "用户/组: $(id -un)/$(id -gn)"
          echo "主机名: $(hostname)"
          echo "IP地址: $(hostname -I)"
          
      - name: 检出代码
        uses: actions/checkout@main
      
      - name: 配置Python运行环境
        uses: actions/setup-python@main
        with:
          python-version: '3.x'

      - name: 安装PyGithub
        run: |
          python -m pip install --upgrade pip
          python -m pip install PyGithub

      - name: 删除旧版本固件和标签
        run: python delete_releases_and_tags.py          
