name: lede-x86_64

on:
  schedule:
    - cron: 0 18 * * *
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install compilation dependencies
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
          git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
          libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
          mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
          libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
          vim wget xmlto xxd zlib1g-dev
          sudo apt autoremove --purge -y
          sudo apt clean -y

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          repository: coolsnowwolf/lede
          ref: master

      - name: Set default manage ip
        run: |
          sed -i 's/192.168.1.1/192.168.5.1/g' package/base-files/files/bin/config_generate

      - name: Edit feeds.conf.default
        run: |
          sed -i 's/^#\(.*helloworld\)/\1/' feeds.conf.default

      - name: Update & install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Make default config
        run: |
          echo "CONFIG_TARGET_x86=y" > .config
          echo "CONFIG_TARGET_x86_64=y" >> .config
          echo "CONFIG_TARGET_x86_64_DEVICE_generic=y" >> .config
          echo "CONFIG_GRUB_IMAGES=y" >> .config
          echo "CONFIG_QCOW2_IMAGES=y" >> .config
          echo "# CONFIG_TARGET_IMAGES_GZIP is not set" >> .config
          make defconfig

      - name: Make download
        run: |
          make download -j8

      - name: Make
        run: |
          make V=s -j2

      - name: Set tag
        id: tag
        run: |
          tag=$(date +"v%Y.%m.%d")
          echo "tag=$tag" >> $GITHUB_OUTPUT

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          files: bin/targets/x86/64/*
          tag_name: ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
          body: |
            ## 说明
            1. 本固件基于 [coolsnowwolf/lede](https://github.com/coolsnowwolf/lede) 自动编译而成，适用于x86_64平台
            2. 本固件在默认配置的基础上，增加helloworld，增加非EFI和QCOW2格式固件，并且取消GZIP压缩
            3. 本固件默认管理地址为： [http://192.168.5.1](http://192.168.5.1) ，用户名：root，密码：password
